FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y python3 python3-pip 
RUN apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
RUN apt-get install -y texlive-xetex texlive-math-extra
RUN apt-get install -y unzip
RUN apt-get install -y locales
RUN locale-gen en pt
RUN update-locale