FROM node:11.14
ENV MYSQL_HOST="mysql"
ENV DATABASE_URL="mysql://root:vitaes@mysql:3306/vitaes"
WORKDIR /vitaes
COPY package.json tsconfig.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn generate
CMD ["yarn", "dev"]
